In [16]:
import os

from dotenv import load_dotenv
from openaq import OpenAQ

load_dotenv()

api_key = os.getenv("OPENAQ_API_KEY")

if not api_key:
    raise ValueError("No se encontró OPENAQ_API_KEY en .env")

client = OpenAQ(api_key=api_key)

In [17]:
locations = client.locations.list(
    parameters_id=2,
    limit=1000
)

In [18]:
type(locations)

openaq.core.responses.LocationsResponse

In [19]:
locations.results[:1]

[Location(id=3, name='NMA - Nima', locality=None, timezone='Africa/Accra', country=CountryBase(id=152, code='GH', name='Ghana'), owner=OwnerBase(id=4, name='Unknown Governmental Organization'), provider=ProviderBase(id=209, name='Dr. Raphael E. Arku and Colleagues'), is_mobile=False, is_monitor=True, instruments=[InstrumentBase(id=2, name='Government Monitor')], sensors=[SensorBase(id=6, name='pm10 µg/m³', parameter=ParameterBase(id=1, name='pm10', units='µg/m³', display_name='PM10')), SensorBase(id=5, name='pm25 µg/m³', parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name='PM2.5'))], coordinates=Coordinates(latitude=5.58389, longitude=-0.19968), bounds=(-0.19968, 5.58389, -0.19968, 5.58389), distance=None, datetime_first=None, datetime_last=None)]

In [20]:
client.close()

In [21]:
some_location = locations.results[10]

print(some_location.name)
print(some_location.country.code)
print(some_location.sensors)

Delhi Technological University, Delhi - CPCB
IN
[SensorBase(id=13866, name='no2 µg/m³', parameter=ParameterBase(id=5, name='no2', units='µg/m³', display_name='NO₂ mass')), SensorBase(id=24, name='o3 µg/m³', parameter=ParameterBase(id=3, name='o3', units='µg/m³', display_name='O₃ mass')), SensorBase(id=13864, name='pm25 µg/m³', parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name='PM2.5'))]

In [22]:
for location in locations.results[:5]:
    print(f"Ubicación: {location.name}")
    print(f"País: {location.country.name} ({location.country.code})")
    print(f"Coordenadas: {location.coordinates.latitude}, {location.coordinates.longitude}")
    
    for sensor in location.sensors:
        print(
                f"  - Sensor {sensor.id}: "
                f"{sensor.parameter.display_name} "
                f"({sensor.parameter.units})"
            )

Ubicación: NMA - Nima
País: Ghana (GH)
Coordenadas: 5.58389, -0.19968
  - Sensor 6: PM10 (µg/m³)
  - Sensor 5: PM2.5 (µg/m³)
Ubicación: NMT - Nima
País: Ghana (GH)
Coordenadas: 5.58165, -0.19898
  - Sensor 7: PM10 (µg/m³)
  - Sensor 8: PM2.5 (µg/m³)
Ubicación: JTA - Jamestown
País: Ghana (GH)
Coordenadas: 5.5401139, -0.2103972
  - Sensor 10: PM10 (µg/m³)
  - Sensor 9: PM2.5 (µg/m³)
Ubicación: ADT - Asylum Down
País: Ghana (GH)
Coordenadas: 5.570722, -0.2120555
  - Sensor 11: PM10 (µg/m³)
  - Sensor 12: PM2.5 (µg/m³)
Ubicación: ADEPA - Asylum Down
País: Ghana (GH)
Coordenadas: 5.567833, -0.2040278
  - Sensor 14: PM10 (µg/m³)
  - Sensor 13: PM2.5 (µg/m³)

In [23]:
help(client.locations.list)

Help on method list in module openaq.models.locations:

list(
    page: int = 1,
    limit: int = 100,
    radius: int | None = None,
    coordinates: tuple[float, float] | None = None,
    bbox: tuple[float, float, float, float] | None = None,
    providers_id: int | list[int] | None = None,
    countries_id: int | list[int] | None = None,
    parameters_id: int | list[int] | None = None,
    licenses_id: int | list[int] | None = None,
    instruments_id: int | list[int] | None = None,
    manufacturers_id: int | list[int] | None = None,
    owners_id: int | list[int] | None = None,
    iso: str | None = None,
    monitor: bool | None = None,
    mobile: bool | None = None,
    order_by: str | None = None,
    sort_order: SortOrder | None = None
) -> LocationsResponse method of openaq.models.locations.Locations instance
    List locations based on provided filters.

    Args:
        page: Page number to retrieve, must be greater than zero.
            Page count is calculated as total locations / limit.
        limit: Number of results per page. Must be between 1 and 1,000.
        radius: Search radius in meters around the coordinates point.
            Must be between 1 and 25,000 (25km).
        coordinates: WGS 84 coordinate pair as (latitude, longitude).
        bbox: Geospatial bounding box as (min_x, min_y, max_x, max_y)
            in WGS 84 coordinates. Limited to four decimal places.
        providers_id: Filter locations by provider ID(s).
            Accepts a single ID or list of IDs.
        countries_id: Filter locations by country ID(s).
            Accepts a single ID or list of IDs.
        parameters_id: Filter locations by parameter ID(s).
            Accepts a single ID or list of IDs.
        licenses_id: Filter locations by license ID(s).
            Accepts a single ID or list of IDs.
        instruments_id: Filter locations by instrument ID(s).
            Accepts a single ID or list of IDs.
        manufacturers_id: Filter locations by manufacturer ID(s).
            Accepts a single ID or list of IDs.
        owners_id: Filter locations by owner ID(s).
            Accepts a single ID or list of IDs.
        iso: Filter locations by 2-letter ISO 3166-alpha-2 country code.
        monitor: Filter by monitor type. True for reference grade monitors,
            False for air sensors.
        mobile: Filter by mobility. True for mobile locations,
            False for stationary locations.
        order_by: Field name to sort results by.
        sort_order: Sort direction, either 'asc' or 'desc'.

    Returns:
        LocationsResponse: An instance representing the list of retrieved locations.

    Raises:
        InvalidParameterError: Client validation error, query parameter is not correct type or value.
        IdentifierOutOfBoundsError: Client validation error, identifier outside support int32 range.
        ApiKeyMissingError: Authentication error, missing API Key credentials.
        BadRequestError: Raised for HTTP 400 error, indicating a client request error.
        NotAuthorizedError: Raised for HTTP 401 error, indicating the client is not authorized.
        ForbiddenError: Raised for HTTP 403 error, indicating the request is forbidden.
        NotFoundError: Raised for HTTP 404 error, indicating a resource is not found.
        TimeoutError: Raised for HTTP 408 error, indicating the request has timed out.
        ValidationError: Raised for HTTP 422 error, indicating invalid request parameters.
        RateLimitError: Raised when managed client exceeds rate limit.
        HTTPRateLimitError: Raised for HTTP 429 error, indicating rate limit exceeded.
        ServerError: Raised for HTTP 500 error, indicating an internal server error or unexpected server-side issue.
        BadGatewayError: Raised for HTTP 502, indicating that the gateway or proxy received an invalid response from the upstream server.
        ServiceUnavailableError: Raised for HTTP 503, indicating that the server is not ready to handle the request.
        GatewayTimeoutError: Raised for HTTP 504 error, indicating a gateway timeout.

In [24]:
countries = client.countries.list(limit=1000)

for country in countries.results:
    if country.code == "AR":
        print(country)

Country(id=6, code='AR', name='Argentina', datetime_first='2016-01-01T03:00:00Z', datetime_last='2026-09-10T03:00:00Z', parameters=[ParameterBase(id=1, name='pm10', units='µg/m³', display_name=None), ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), ParameterBase(id=3, name='o3', units='µg/m³', display_name=None), ParameterBase(id=4, name='co', units='µg/m³', display_name=None), ParameterBase(id=5, name='no2', units='µg/m³', display_name=None), ParameterBase(id=6, name='so2', units='µg/m³', display_name=None), ParameterBase(id=7, name='no2', units='ppm', display_name=None), ParameterBase(id=8, name='co', units='ppm', display_name=None), ParameterBase(id=19, name='pm1', units='µg/m³', display_name=None), ParameterBase(id=27, name='nox', units='µg/m³', display_name=None), ParameterBase(id=95, name='pressure', units='hpa', display_name=None), ParameterBase(id=98, name='relativehumidity', units='%', display_name=None), ParameterBase(id=100, name='temperature', units='c', display_name=None), ParameterBase(id=125, name='um003', units='particles/cm³', display_name=None), ParameterBase(id=128, name='temperature', units='f', display_name=None), ParameterBase(id=19843, name='no', units='µg/m³', display_name=None)])

In [25]:
locations_ar = client.locations.list(
    countries_id=6,
    parameters_id=2,
    limit=100
)

In [59]:
for location in locations_ar.results:
    print(f"Nombre: {location.name}")
    print(f"Id: {location.id}")
    print(f"País: {location.country.name} ({location.country.code})")
    print(f"Coordenadas: {location.coordinates.latitude}, {location.coordinates.longitude}")
    
    for sensor in location.sensors:
            print(
                    f"  - Sensor {sensor.id}: "
                    f"{sensor.parameter.display_name} "
                    f"({sensor.parameter.units})"
                )

Nombre: SPARTAN - CITEDEF
Id: 14
País: Argentina (AR)
Coordenadas: -34.56, -58.506
  - Sensor 25: PM2.5 (µg/m³)
Nombre: Buenos Aires
Id: 225349
País: Argentina (AR)
Coordenadas: -34.5766, -58.4188
  - Sensor 1303159: PM2.5 (µg/m³)
Nombre: EMC I Dock Sud
Id: 1212895
País: Argentina (AR)
Coordenadas: -34.667375, -58.329231
  - Sensor 6512235: CO mass (µg/m³)
  - Sensor 6512232: NO mass (µg/m³)
  - Sensor 6512236: NO₂ mass (µg/m³)
  - Sensor 6512233: NOx mass (µg/m³)
  - Sensor 6514051: O₃ mass (µg/m³)
  - Sensor 6512239: PM10 (µg/m³)
  - Sensor 6512234: PM2.5 (µg/m³)
  - Sensor 6514050: SO₂ mass (µg/m³)
Nombre: EMC II La Matanza
Id: 1212896
País: Argentina (AR)
Coordenadas: -34.883175, -58.682542000000005
  - Sensor 6514630: CO mass (µg/m³)
  - Sensor 6512230: NO mass (µg/m³)
  - Sensor 6512237: NO₂ mass (µg/m³)
  - Sensor 6512231: NOx mass (µg/m³)
  - Sensor 6512228: O₃ mass (µg/m³)
  - Sensor 6512229: PM10 (µg/m³)
  - Sensor 6514631: PM2.5 (µg/m³)
  - Sensor 6512238: SO₂ mass (µg/m³)
Nombre: SPARTAN - CITEDEF
Id: 1285340
País: Argentina (AR)
Coordenadas: -34.5554, -58.5064
  - Sensor 6566255: PM2.5 (µg/m³)
Nombre: AirGradient Saladillo
Id: 1385668
País: Argentina (AR)
Coordenadas: -35.64627885582698, -59.78680330642245
  - Sensor 6690069: PM2.5 (µg/m³)
  - Sensor 6690065: Temperature (C) (c)
Nombre: AirGradient Saladillo Indoor
Id: 1392600
País: Argentina (AR)
Coordenadas: -35.64627885582698, -59.78680330642245
  - Sensor 6701250: PM2.5 (µg/m³)
  - Sensor 6701243: Temperature (C) (c)
Nombre: AirGradient Saladillo
Id: 1485626
País: Argentina (AR)
Coordenadas: -35.645393865353256, -59.78567136420022
  - Sensor 6831443: PM2.5 (µg/m³)
  - Sensor 6831431: Temperature (C) (c)
Nombre: saladillo_urban_1
Id: 1658093
País: Argentina (AR)
Coordenadas: -35.63367238352178, -59.77516515137027
  - Sensor 7979006: PM1 (µg/m³)
  - Sensor 7971136: PM1 (µg/m³)
  - Sensor 7971166: PM10 (µg/m³)
  - Sensor 7979004: PM10 (µg/m³)
  - Sensor 7107254: PM2.5 (µg/m³)
  - Sensor 7972590: RH (%)
  - Sensor 7107255: Temperature (C) (c)
  - Sensor 7972592: PM0.3 count (particles/cm³)
Nombre: Argentina EP15 - Saladillo
Id: 1894631
País: Argentina (AR)
Coordenadas: -35.68277, -59.76544
  - Sensor 7466388: PM1 (µg/m³)
  - Sensor 7466389: PM10 (µg/m³)
  - Sensor 7466390: PM2.5 (µg/m³)
  - Sensor 7466391: Temperature (C) (c)
  - Sensor 7466392: Temperature (F) (f)
Nombre: Luciano, Argentina Facultad de Informática UNLP (DISAB7040 → A4QP99VT)
Id: 1894638
País: Argentina (AR)
Coordenadas: -34.903448, -57.937651
  - Sensor 7466353: PM1 (µg/m³)
  - Sensor 7466354: PM10 (µg/m³)
  - Sensor 7466355: PM2.5 (µg/m³)
  - Sensor 7466356: Temperature (C) (c)
  - Sensor 7466357: Temperature (F) (f)
Nombre: La Matanza, Buenos Aires
Id: 2099180
País: Argentina (AR)
Coordenadas: -34.88106631929777, -58.68288039022074
  - Sensor 8562534: PM1 (µg/m³)
  - Sensor 8562542: PM10 (µg/m³)
  - Sensor 7696815: PM2.5 (µg/m³)
  - Sensor 8562586: RH (%)
  - Sensor 7696814: Temperature (C) (c)
  - Sensor 8562589: PM0.3 count (particles/cm³)
Nombre: EET1_Saladillo
Id: 2798193
País: Argentina (AR)
Coordenadas: -35.6442117793875, -59.783312717343826
  - Sensor 8929514: PM1 (µg/m³)
  - Sensor 8929517: PM10 (µg/m³)
  - Sensor 8929519: PM2.5 (µg/m³)
  - Sensor 8929520: RH (%)
  - Sensor 8929522: Temperature (C) (c)
  - Sensor 8929516: PM0.3 count (particles/cm³)
Nombre: Adrogué
Id: 2847298
País: Argentina (AR)
Coordenadas: -34.79488517026303, -58.40140165642574
  - Sensor 9224176: PM1 (µg/m³)
  - Sensor 9224189: PM10 (µg/m³)
  - Sensor 9224161: PM2.5 (µg/m³)
  - Sensor 9224186: RH (%)
  - Sensor 9224200: Temperature (C) (c)
  - Sensor 9224174: PM0.3 count (particles/cm³)
Nombre: Dock Sud, Buenos Aires
Id: 2847299
País: Argentina (AR)
Coordenadas: -34.667282, -58.32922
  - Sensor 9224197: PM1 (µg/m³)
  - Sensor 9224166: PM10 (µg/m³)
  - Sensor 9224148: PM2.5 (µg/m³)
  - Sensor 9224168: RH (%)
  - Sensor 9224167: Temperature (C) (c)
  - Sensor 9224147: PM0.3 count (particles/cm³)
Nombre: Saladillo Centro
Id: 2874879
País: Argentina (AR)
Coordenadas: -35.63386558517702, -59.77481854387068
  - Sensor 9430771: PM1 (µg/m³)
  - Sensor 9430772: PM10 (µg/m³)
  - Sensor 9430768: PM2.5 (µg/m³)
  - Sensor 9430767: RH (%)
  - Sensor 9430769: Temperature (C) (c)
  - Sensor 9430770: PM0.3 count (particles/cm³)
Nombre: Avenida Raul Scalabrini Ortiz 1355, Palermo, Buenos Aires, Argentina
Id: 6181244
País: Argentina (AR)
Coordenadas: -34.592443667902096, -58.427418773018125
  - Sensor 15012776: PM1 (µg/m³)
  - Sensor 15012777: PM2.5 (µg/m³)
  - Sensor 15012778: RH (%)
  - Sensor 15012779: Temperature (C) (c)
  - Sensor 15012780: PM0.3 count (particles/cm³)
Nombre: La Plata
Id: 6264701
País: Argentina (AR)
Coordenadas: -34.900091, -57.924198
  - Sensor 15629783: PM1 (µg/m³)
  - Sensor 15629784: PM2.5 (µg/m³)
  - Sensor 15629785: RH (%)
  - Sensor 15629786: Temperature (C) (c)
  - Sensor 15629787: PM0.3 count (particles/cm³)
Nombre: Neuquen - Plottier - Hospital
Id: 6347224
País: Argentina (AR)
Coordenadas: -38.94971106095227, -68.22794371149313
  - Sensor 16246049: PM1 (µg/m³)
  - Sensor 16246050: PM2.5 (µg/m³)
  - Sensor 16246051: RH (%)
  - Sensor 16246052: Temperature (C) (c)
  - Sensor 16246053: PM0.3 count (particles/cm³)
Nombre: San Patricio Del Chañar - Dirección De Ambiente
Id: 6347411
País: Argentina (AR)
Coordenadas: -38.63198804182453, -68.29644313035016
  - Sensor 16247466: PM1 (µg/m³)
  - Sensor 16247467: PM2.5 (µg/m³)
  - Sensor 16247468: RH (%)
  - Sensor 16247469: Temperature (C) (c)
  - Sensor 16247470: PM0.3 count (particles/cm³)
Nombre: Colonia Rural - CdS Nueva Esperanza
Id: 6347503
País: Argentina (AR)
Coordenadas: -38.90492729989632, -68.13547073011814
  - Sensor 16248167: PM1 (µg/m³)
  - Sensor 16248168: PM2.5 (µg/m³)
  - Sensor 16248169: RH (%)
  - Sensor 16248170: Temperature (C) (c)
  - Sensor 16248171: PM0.3 count (particles/cm³)
Nombre: Zapala - CIC Caleuche
Id: 6348815
País: Argentina (AR)
Coordenadas: -38.88950338188707, -70.05847323797107
  - Sensor 16258058: PM1 (µg/m³)
  - Sensor 16258059: PM2.5 (µg/m³)
  - Sensor 16258060: RH (%)
  - Sensor 16258061: Temperature (C) (c)
  - Sensor 16258062: PM0.3 count (particles/cm³)
Nombre: San Martin De Los Andes - Chacra 4
Id: 6349056
País: Argentina (AR)
Coordenadas: -40.14744765872663, -71.30714630790116
  - Sensor 16259752: PM1 (µg/m³)
  - Sensor 16259753: PM2.5 (µg/m³)
  - Sensor 16259754: RH (%)
  - Sensor 16259755: Temperature (C) (c)
  - Sensor 16259756: PM0.3 count (particles/cm³)
Nombre: Añelo - Hospital
Id: 6366576
País: Argentina (AR)
Coordenadas: -38.3542671, -68.7799657
  - Sensor 16349163: PM1 (µg/m³)
  - Sensor 16349164: PM2.5 (µg/m³)
  - Sensor 16349165: RH (%)
  - Sensor 16349166: Temperature (C) (c)
  - Sensor 16349167: PM0.3 count (particles/cm³)
Nombre: NW_7
Id: 6379680
País: Argentina (AR)
Coordenadas: -26.8342, -65.2049
  - Sensor 16445943: PM1 (µg/m³)
  - Sensor 16445944: PM10 (µg/m³)
  - Sensor 16445945: PM2.5 (µg/m³)
  - Sensor 16445946: Atmospheric pressure (hpa)
  - Sensor 16445947: RH (%)
  - Sensor 16445948: Temperature (C) (c)
Nombre: NW_34
Id: 6379681
País: Argentina (AR)
Coordenadas: -26.7222, -66.0668
  - Sensor 16445967: PM1 (µg/m³)
  - Sensor 16445968: PM10 (µg/m³)
  - Sensor 16445969: PM2.5 (µg/m³)
  - Sensor 16445970: Atmospheric pressure (hpa)
  - Sensor 16445971: RH (%)
  - Sensor 16445972: Temperature (C) (c)
Nombre: NW_35
Id: 6379682
País: Argentina (AR)
Coordenadas: -24.7404, -65.3919
  - Sensor 16445949: PM1 (µg/m³)
  - Sensor 16445950: PM10 (µg/m³)
  - Sensor 16445951: PM2.5 (µg/m³)
  - Sensor 16445952: Atmospheric pressure (hpa)
  - Sensor 16445953: RH (%)
  - Sensor 16445954: Temperature (C) (c)
Nombre: NW_30
Id: 6379683
País: Argentina (AR)
Coordenadas: -27.7844, -64.2669
  - Sensor 16445979: PM1 (µg/m³)
  - Sensor 16445980: PM10 (µg/m³)
  - Sensor 16445981: PM2.5 (µg/m³)
  - Sensor 16445982: Atmospheric pressure (hpa)
  - Sensor 16445983: RH (%)
  - Sensor 16445984: Temperature (C) (c)
Nombre: NW_40
Id: 6379684
País: Argentina (AR)
Coordenadas: -26.8012, -60.44800000000001
  - Sensor 16445985: PM1 (µg/m³)
  - Sensor 16445986: PM10 (µg/m³)
  - Sensor 16445987: PM2.5 (µg/m³)
  - Sensor 16445988: Atmospheric pressure (hpa)
  - Sensor 16445989: RH (%)
  - Sensor 16445990: Temperature (C) (c)
Nombre: NW_41
Id: 6379685
País: Argentina (AR)
Coordenadas: -27.4591, -58.8223
  - Sensor 16445961: PM1 (µg/m³)
  - Sensor 16445962: PM10 (µg/m³)
  - Sensor 16445963: PM2.5 (µg/m³)
  - Sensor 16445964: Atmospheric pressure (hpa)
  - Sensor 16445965: RH (%)
  - Sensor 16445966: Temperature (C) (c)
Nombre: NW_42
Id: 6379686
País: Argentina (AR)
Coordenadas: -29.0925, -67.2815
  - Sensor 16521014: PM1 (µg/m³)
  - Sensor 16521015: PM10 (µg/m³)
  - Sensor 16521016: PM2.5 (µg/m³)
  - Sensor 16521017: Atmospheric pressure (hpa)
  - Sensor 16521018: RH (%)
  - Sensor 16521019: Temperature (C) (c)
Nombre: NW_45
Id: 6379687
País: Argentina (AR)
Coordenadas: -27.3646, -55.894
  - Sensor 16445955: PM1 (µg/m³)
  - Sensor 16445956: PM10 (µg/m³)
  - Sensor 16445957: PM2.5 (µg/m³)
  - Sensor 16445958: Atmospheric pressure (hpa)
  - Sensor 16445959: RH (%)
  - Sensor 16445960: Temperature (C) (c)
Nombre: NW_46
Id: 6379688
País: Argentina (AR)
Coordenadas: -24.2511, -65.2025
  - Sensor 16445973: PM1 (µg/m³)
  - Sensor 16445974: PM10 (µg/m³)
  - Sensor 16445975: PM2.5 (µg/m³)
  - Sensor 16445976: Atmospheric pressure (hpa)
  - Sensor 16445977: RH (%)
  - Sensor 16445978: Temperature (C) (c)
Nombre: NW_48
Id: 6379689
País: Argentina (AR)
Coordenadas: -26.2396, -58.24730000000001
  - Sensor 16669737: PM1 (µg/m³)
  - Sensor 16669738: PM10 (µg/m³)
  - Sensor 16669739: PM2.5 (µg/m³)
  - Sensor 16669740: Atmospheric pressure (hpa)
  - Sensor 16669741: RH (%)
  - Sensor 16669742: Temperature (C) (c)
Nombre: Chos Malal - Escuela N° 15
Id: 6383988
País: Argentina (AR)
Coordenadas: -37.3865915, -70.2623088
  - Sensor 16477677: PM1 (µg/m³)
  - Sensor 16477678: PM2.5 (µg/m³)
  - Sensor 16477679: RH (%)
  - Sensor 16477680: Temperature (C) (c)
  - Sensor 16477681: PM0.3 count (particles/cm³)
Nombre: Despeñaderos - Espacio Gastronómico
Id: 6386898
País: Argentina (AR)
Coordenadas: -31.81568182259808, -64.29168833153683
  - Sensor 16499121: PM1 (µg/m³)
  - Sensor 16499122: PM2.5 (µg/m³)
  - Sensor 16499123: RH (%)
  - Sensor 16499124: Temperature (C) (c)
  - Sensor 16499125: PM0.3 count (particles/cm³)
Nombre: Oncativo - Centro
Id: 6386995
País: Argentina (AR)
Coordenadas: -31.913350615273654, -63.68143313227694
  - Sensor 16499800: PM1 (µg/m³)
  - Sensor 16499801: PM2.5 (µg/m³)
  - Sensor 16499802: RH (%)
  - Sensor 16499803: Temperature (C) (c)
  - Sensor 16499804: PM0.3 count (particles/cm³)
Nombre: Agua De Oro - CAPS
Id: 6388171
País: Argentina (AR)
Coordenadas: -31.06558062094667, -64.30205976351887
  - Sensor 16508393: PM1 (µg/m³)
  - Sensor 16508394: PM2.5 (µg/m³)
  - Sensor 16508395: RH (%)
  - Sensor 16508396: Temperature (C) (c)
  - Sensor 16508397: PM0.3 count (particles/cm³)
Nombre: San Francisco - Servicios Públicos
Id: 6389820
País: Argentina (AR)
Coordenadas: -31.425132, -62.070393
  - Sensor 16520681: PM1 (µg/m³)
  - Sensor 16520682: PM2.5 (µg/m³)
  - Sensor 16520683: RH (%)
  - Sensor 16520684: Temperature (C) (c)
  - Sensor 16520685: PM0.3 count (particles/cm³)
Nombre: Villa Dolores - Centro
Id: 6398515
País: Argentina (AR)
Coordenadas: -31.942874952862326, -65.19013298754992
  - Sensor 16584822: PM1 (µg/m³)
  - Sensor 16584823: PM2.5 (µg/m³)
  - Sensor 16584824: RH (%)
  - Sensor 16584825: Temperature (C) (c)
  - Sensor 16584826: PM0.3 count (particles/cm³)
Nombre: Villa Maria - Municipalidad
Id: 6401192
País: Argentina (AR)
Coordenadas: -32.415374, -63.242446
  - Sensor 16604681: PM1 (µg/m³)
  - Sensor 16604682: PM2.5 (µg/m³)
  - Sensor 16604683: RH (%)
  - Sensor 16604684: Temperature (C) (c)
  - Sensor 16604685: PM0.3 count (particles/cm³)
Nombre: INGREM consultora de ingeneria
Id: 6474504
País: Argentina (AR)
Coordenadas: -31.749081, -60.525913
  - Sensor 17141840: PM1 (µg/m³)
  - Sensor 17141841: PM2.5 (µg/m³)
  - Sensor 17141842: RH (%)
  - Sensor 17141843: Temperature (C) (c)
  - Sensor 17141844: PM0.3 count (particles/cm³)
Nombre: Toay - Esc. Secundaria “Olga Orozco”
Id: 6488963
País: Argentina (AR)
Coordenadas: -36.668466, -64.363419
  - Sensor 17247949: PM1 (µg/m³)
  - Sensor 17247950: PM2.5 (µg/m³)
  - Sensor 17247951: RH (%)
  - Sensor 17247952: Temperature (C) (c)
  - Sensor 17247953: PM0.3 count (particles/cm³)
Nombre: Toay - Av. Perón
Id: 6499794
País: Argentina (AR)
Coordenadas: -36.649223, -64.334167
  - Sensor 17327332: PM1 (µg/m³)
  - Sensor 17327333: PM2.5 (µg/m³)
  - Sensor 17327334: RH (%)
  - Sensor 17327335: Temperature (C) (c)
  - Sensor 17327336: PM0.3 count (particles/cm³)
Nombre: El Pedregoso
Id: 6503511
País: Argentina (AR)
Coordenadas: -42.10403, -71.44551
  - Sensor 17354635: PM1 (µg/m³)
  - Sensor 17354636: PM2.5 (µg/m³)
  - Sensor 17354637: RH (%)
  - Sensor 17354638: Temperature (C) (c)
  - Sensor 17354639: PM0.3 count (particles/cm³)

In [27]:
candidate_sensors = {
    "Buenos Aires": 1303159,
    "EMC I Dock Sud": 6512234,
    "EMC II La Matanza": 6514631,
    "Palermo": 15012777,
}

for station_name, sensor_id in candidate_sensors.items():
    response = client.measurements.list(data="days",
        sensors_id=sensor_id,
        limit=5
    )

    print(f"\n--- {station_name} | sensor {sensor_id} ---")
    print(response.results[:2])

--- Buenos Aires | sensor 1303159 ---
[Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2021-04-28T03:00:00Z', local='2021-04-28T00:00:00-03:00'), datetime_to=Datetime(utc='2021-04-29T03:00:00Z', local='2021-04-29T00:00:00-03:00')), value=10.0, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=10.0, q02=10.0, q25=10.0, median=10.0, q75=10.0, q98=10.0, max=10.0, sd=None, avg=10.0), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=1, observed_interval='01:00:00', percent_complete=4.0, percent_coverage=4.0, datetime_from=Datetime(utc='2021-04-28T16:00:00Z', local='2021-04-28T13:00:00-03:00'), datetime_to=Datetime(utc='2021-04-28T16:00:00Z', local='2021-04-28T13:00:00-03:00'))), Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2021-05-06T03:00:00Z', local='2021-05-06T00:00:00-03:00'), datetime_to=Datetime(utc='2021-05-07T03:00:00Z', local='2021-05-07T00:00:00-03:00')), value=5.0, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=5.0, q02=5.0, q25=5.0, median=5.0, q75=5.0, q98=5.0, max=5.0, sd=None, avg=5.0), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=1, observed_interval='01:00:00', percent_complete=4.0, percent_coverage=4.0, datetime_from=Datetime(utc='2021-05-06T17:00:00Z', local='2021-05-06T14:00:00-03:00'), datetime_to=Datetime(utc='2021-05-06T17:00:00Z', local='2021-05-06T14:00:00-03:00')))]

--- EMC I Dock Sud | sensor 6512234 ---
[Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2023-07-13T03:00:00Z', local='2023-07-13T00:00:00-03:00'), datetime_to=Datetime(utc='2023-07-14T03:00:00Z', local='2023-07-14T00:00:00-03:00')), value=18.0, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=12.0, q02=12.24, q25=15.0, median=18.0, q75=21.0, q98=23.759999999999998, max=24.0, sd=8.48528137423857, avg=18.0), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=2, observed_interval='02:00:00', percent_complete=8.0, percent_coverage=8.0, datetime_from=Datetime(utc='2023-07-13T13:00:00Z', local='2023-07-13T10:00:00-03:00'), datetime_to=Datetime(utc='2023-07-13T14:00:00Z', local='2023-07-13T11:00:00-03:00'))), Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2023-07-14T03:00:00Z', local='2023-07-14T00:00:00-03:00'), datetime_to=Datetime(utc='2023-07-15T03:00:00Z', local='2023-07-15T00:00:00-03:00')), value=20.5, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=18.0, q02=18.1, q25=19.25, median=20.5, q75=21.75, q98=22.9, max=23.0, sd=3.5355339059327378, avg=20.5), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=2, observed_interval='02:00:00', percent_complete=8.0, percent_coverage=8.0, datetime_from=Datetime(utc='2023-07-14T06:00:00Z', local='2023-07-14T03:00:00-03:00'), datetime_to=Datetime(utc='2023-07-14T13:00:00Z', local='2023-07-14T10:00:00-03:00')))]

--- EMC II La Matanza | sensor 6514631 ---
[Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2023-07-13T03:00:00Z', local='2023-07-13T00:00:00-03:00'), datetime_to=Datetime(utc='2023-07-14T03:00:00Z', local='2023-07-14T00:00:00-03:00')), value=1.0, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=1.0, q02=1.0, q25=1.0, median=1.0, q75=1.0, q98=1.0, max=1.0, sd=0.0, avg=1.0), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=2, observed_interval='02:00:00', percent_complete=8.0, percent_coverage=8.0, datetime_from=Datetime(utc='2023-07-13T13:00:00Z', local='2023-07-13T10:00:00-03:00'), datetime_to=Datetime(utc='2023-07-13T14:00:00Z', local='2023-07-13T11:00:00-03:00'))), Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2023-07-17T03:00:00Z', local='2023-07-17T00:00:00-03:00'), datetime_to=Datetime(utc='2023-07-18T03:00:00Z', local='2023-07-18T00:00:00-03:00')), value=1.0, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=1.0, q02=1.0, q25=1.0, median=1.0, q75=1.0, q98=1.0, max=1.0, sd=0.0, avg=1.0), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=6, observed_interval='06:00:00', percent_complete=25.0, percent_coverage=25.0, datetime_from=Datetime(utc='2023-07-17T05:00:00Z', local='2023-07-17T02:00:00-03:00'), datetime_to=Datetime(utc='2023-07-17T16:00:00Z', local='2023-07-17T13:00:00-03:00')))]

--- Palermo | sensor 15012777 ---
[Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2025-12-28T03:00:00Z', local='2025-12-28T00:00:00-03:00'), datetime_to=Datetime(utc='2025-12-29T03:00:00Z', local='2025-12-29T00:00:00-03:00')), value=1.19, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=0.0, q02=0.0, q25=0.33033333619435623, median=0.6242499995976685, q75=1.5071666646748783, q98=4.497956687505047, max=4.998500028997659, sd=0.9011237488643632, avg=1.1947470259941404), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=14, observed_interval='14:00:00', percent_complete=58.0, percent_coverage=58.0, datetime_from=Datetime(utc='2025-12-28T14:00:00Z', local='2025-12-28T11:00:00-03:00'), datetime_to=Datetime(utc='2025-12-29T03:00:00Z', local='2025-12-29T00:00:00-03:00'))), Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2025-12-29T03:00:00Z', local='2025-12-29T00:00:00-03:00'), datetime_to=Datetime(utc='2025-12-30T03:00:00Z', local='2025-12-30T00:00:00-03:00')), value=8.15, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=0.016499999910593033, q02=0.0324466667920351, q25=1.347718746168539, median=5.614562504821354, q75=10.602416682243348, q98=25.91301003265381, max=26.533166694641114, sd=9.438520068633611, avg=8.14850000349408), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=24, observed_interval='24:00:00', percent_complete=100.0, percent_coverage=100.0, datetime_from=Datetime(utc='2025-12-29T04:00:00Z', local='2025-12-29T01:00:00-03:00'), datetime_to=Datetime(utc='2025-12-30T03:00:00Z', local='2025-12-30T00:00:00-03:00')))]

In [28]:
from datetime import datetime, timedelta, timezone

end_date = datetime.now(timezone.utc)
start_date = end_date - timedelta(days=14)

palermo_hours = client.measurements.list(data="hours",
                                         sensors_id=15012777,
                                         datetime_from=start_date,
                                         datetime_to=end_date,
                                         limit=1000)

In [29]:
print(f"Cantidad de registros: {len(palermo_hours.results)}")

print("\nPrimer registro:")
#print(palermo_hours.results[0])

print("\nÚltimo registro:")
#print(palermo_hours.results[-1])

Cantidad de registros: 0

Primer registro:

Último registro:

In [30]:
candidate_sensors = {
    "Palermo": 15012777,
    "Adrogué": 9224161,
    "Dock Sud (AirGradient)": 9224148,
    "La Matanza": 7696815,
    "La Plata / UNLP": 7466355,
    "Neuquén - Plottier": 16246050,
}

def check_recent_data(name, sensor_id, days=30):
    end_date = datetime.now(timezone.utc)
    start_date = end_date - timedelta(days=days)

    response = client.measurements.list(
        sensors_id=sensor_id,
        data="hours",
        datetime_from=start_date,
        datetime_to=end_date,
        limit=1000
    )

    records = response.results

    if not records:
        print(f"{name}: sin datos en los últimos {days} días")
        return

    first_date = records[0].period.datetime_from.local
    last_date = records[-1].period.datetime_from.local

    print(
        f"{name}: {len(records)} registros | "
        f"desde {first_date} hasta {last_date}"
    )

In [31]:
for station_name, sensor_id in candidate_sensors.items():
    check_recent_data(station_name,sensor_id)

Palermo: sin datos en los últimos 30 días
Adrogué: sin datos en los últimos 30 días
Dock Sud (AirGradient): sin datos en los últimos 30 días
La Matanza: 716 registros | desde 2026-08-10T19:00:00-03:00 hasta 2026-09-09T18:00:00-03:00
La Plata / UNLP: sin datos en los últimos 30 días
Neuquén - Plottier: 713 registros | desde 2026-08-10T19:00:00-03:00 hasta 2026-09-09T18:00:00-03:00

Sensor elegido: La matanza 7696815, gracias a que posee datos en los utlimos 30 dias y mide mas que solo PM2.5

In [32]:
import pandas as pd

MATANZA_SENSOR = 7696815

matanza_data_hourly = client.measurements.list(sensors_id=MATANZA_SENSOR,
                                               data="hours",
                                               datetime_from=start_date,
                                               datetime_to=end_date,
                                               limit=1000
                                               )

In [33]:
firts_feature = matanza_data_hourly.results[1]
print(firts_feature.period.datetime_from.utc)
print(f"Coverage: {firts_feature.coverage}")
print(f"Type: {firts_feature.parameter.name} in {firts_feature.parameter.units}, value {firts_feature.value}")

2026-08-26T23:00:00Z
Coverage: Coverage(expected_count=1, expected_interval='01:00:00', observed_count=1, observed_interval='01:00:00', percent_complete=100.0, percent_coverage=100.0, datetime_from=Datetime(utc='2026-08-26T23:00:00Z', local='2026-08-26T20:00:00-03:00'), datetime_to=Datetime(utc='2026-08-27T00:00:00Z', local='2026-08-26T21:00:00-03:00'))
Type: pm25 in µg/m³, value 48.3

In [34]:
rows = []

for measurement in matanza_data_hourly.results:
    rows.append({
        "measured_at_utc" : measurement.period.datetime_from.utc,
        "measured_at_local": measurement.period.datetime_from.local,
        "pm25_ug_m3": measurement.value,
        "coverage_pct": measurement.coverage.percent_complete,
        }
    )
    
pm25_df = pd.DataFrame(rows)
pm25_df.head()

        measured_at_utc          measured_at_local  pm25_ug_m3  coverage_pct
0  2026-08-26T22:00:00Z  2026-08-26T19:00:00-03:00        60.7         100.0
1  2026-08-26T23:00:00Z  2026-08-26T20:00:00-03:00        48.3         100.0
2  2026-08-27T00:00:00Z  2026-08-26T21:00:00-03:00        46.8         100.0
3  2026-08-27T01:00:00Z  2026-08-26T22:00:00-03:00        64.0         100.0
4  2026-08-27T02:00:00Z  2026-08-26T23:00:00-03:00        52.3         100.0

In [35]:
pm25_df.shape

(336, 4)

In [36]:
pm25_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   measured_at_utc    336 non-null    str
 1   measured_at_local  336 non-null    str
 2   pm25_ug_m3         336 non-null    float64
 3   coverage_pct       336 non-null    float64
dtypes: float64(2), str(2)
memory usage: 10.6 KB

In [37]:
pm25_df.describe()

       pm25_ug_m3  coverage_pct
count  336.000000         336.0
mean    21.554762         100.0
std     24.132422           0.0
min      0.000000         100.0
25%      4.375000         100.0
50%     11.750000         100.0
75%     32.575000         100.0
max    125.000000         100.0

In [38]:
pm25_df.loc[pm25_df["pm25_ug_m3"] >= 100.0 ]

         measured_at_utc          measured_at_local  pm25_ug_m3  coverage_pct
74  2026-08-30T00:00:00Z  2026-08-29T21:00:00-03:00       103.0         100.0
76  2026-08-30T02:00:00Z  2026-08-29T23:00:00-03:00       115.0         100.0
80  2026-08-30T06:00:00Z  2026-08-30T03:00:00-03:00       106.0         100.0
81  2026-08-30T07:00:00Z  2026-08-30T04:00:00-03:00       125.0         100.0

In [39]:
pm25_df["measured_at_local"] = pd.to_datetime(pm25_df["measured_at_local"])

pm25_df["measured_at_utc"] = pd.to_datetime(pm25_df["measured_at_utc"],utc=True)

In [40]:
pm25_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 336 entries, 0 to 335
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   measured_at_utc    336 non-null    datetime64[us, UTC]
 1   measured_at_local  336 non-null    datetime64[us, UTC-03:00]
 2   pm25_ug_m3         336 non-null    float64
 3   coverage_pct       336 non-null    float64
dtypes: datetime64[us, UTC-03:00](1), datetime64[us, UTC](1), float64(2)
memory usage: 10.6 KB

In [41]:
high_pm = pm25_df.loc[pm25_df["pm25_ug_m3"] >= 100.0]

print(f"{round(high_pm.shape[0] / pm25_df.shape[0] *100, 3)}%")

1.19%

In [42]:
historical_matanza_data = client.measurements.list(sensors_id=7696815,
                                                   data="days",
                                                   date_from="2022-01-01",
                                                   date_to="2026-09-08",
                                                   limit=1000)

historical_matanza_data.results[0]

Measurement(period=Period(label='1day', interval='24:00:00', datetime_from=Datetime(utc='2024-01-15T03:00:00Z', local='2024-01-15T00:00:00-03:00'), datetime_to=Datetime(utc='2024-01-16T03:00:00Z', local='2024-01-16T00:00:00-03:00')), value=1.88, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=0.10833333618938923, q02=0.132821431607008, q25=0.6116269836202264, median=1.9314682632684708, q75=2.419057515760263, q98=4.929710338513056, max=5.201785763104756, sd=1.5865545535260572, avg=1.8842361078760215), coverage=Coverage(expected_count=24, expected_interval='24:00:00', observed_count=12, observed_interval='12:00:00', percent_complete=50.0, percent_coverage=50.0, datetime_from=Datetime(utc='2024-01-15T15:00:00Z', local='2024-01-15T12:00:00-03:00'), datetime_to=Datetime(utc='2024-01-16T03:00:00Z', local='2024-01-16T00:00:00-03:00')))

In [43]:
historical_rows = []

for measurement in historical_matanza_data.results:
    historical_rows.append(
        {
            "period_start_utc": measurement.period.datetime_from.utc,
            "period_start_local": measurement.period.datetime_from.local,
            "pm25_ug_m3": measurement.value,
            "coverage_pct": measurement.coverage.percent_complete,
        }
    )

historical_daily_df = pd.DataFrame(historical_rows)

historical_daily_df["period_start_utc"] = pd.to_datetime(
    historical_daily_df["period_start_utc"],
    utc=True
)

historical_daily_df = historical_daily_df.sort_values(
    "period_start_utc"
).reset_index(drop=True)

In [44]:
print("Primera fecha:", historical_daily_df["period_start_utc"].min())
print("Última fecha:", historical_daily_df["period_start_utc"].max())
print("Días con datos:", len(historical_daily_df))
print("\nCobertura diaria:")
print(historical_daily_df["coverage_pct"].describe())

Primera fecha: 2024-01-15 03:00:00+00:00
Última fecha: 2026-09-08 03:00:00+00:00
Días con datos: 682

Cobertura diaria:
count    682.000000
mean      96.243402
std       12.441794
min        8.000000
25%      100.000000
50%      100.000000
75%      100.000000
max      100.000000
Name: coverage_pct, dtype: float64

In [45]:
historical_daily_df["gap_days"] = (
    historical_daily_df["period_start_utc"]
    .diff()
    .dt.total_seconds()
    .div(86_400)
)

gaps = historical_daily_df.loc[
    historical_daily_df["gap_days"] > 1,
    ["period_start_utc", "gap_days"]
]

gaps.head(20)

             period_start_utc  gap_days
3   2024-01-19 03:00:00+00:00       2.0
4   2024-01-22 03:00:00+00:00       3.0
7   2024-03-21 03:00:00+00:00      57.0
9   2024-03-25 03:00:00+00:00       3.0
10  2024-04-23 03:00:00+00:00      29.0
12  2024-05-15 03:00:00+00:00      21.0
35  2024-08-29 03:00:00+00:00      84.0
36  2024-09-17 03:00:00+00:00      19.0
44  2024-09-26 03:00:00+00:00       2.0
152 2025-01-13 03:00:00+00:00       2.0
153 2025-02-11 03:00:00+00:00      29.0
211 2025-04-11 03:00:00+00:00       2.0
252 2025-05-23 03:00:00+00:00       2.0
342 2025-09-25 03:00:00+00:00      36.0
471 2026-02-10 03:00:00+00:00      10.0

In [1]:
import os

from dotenv import load_dotenv
from openaq import OpenAQ

load_dotenv()

api_key = os.getenv("OPENAQ_API_KEY")

if not api_key:
    raise ValueError("No se encontró OPENAQ_API_KEY en .env")

client = OpenAQ(api_key=api_key)

In [23]:
last_matanza = client.locations.latest(locations_id=2099180)

In [24]:
last_matanza

LatestResponse(headers=Headers(x_ratelimit_limit=60, x_ratelimit_remaining=59, x_ratelimit_used=1, x_ratelimit_reset=60), meta=Meta(name='openaq-api', website='/', page=1, limit=100, found=6), results=[Latest(datetime=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'), value=17.7, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=8562534, locations_id=2099180), Latest(datetime=Datetime(utc='2025-01-13T23:00:00Z', local='2025-01-13T20:00:00-03:00'), value=9.255555550257364, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=8562542, locations_id=2099180), Latest(datetime=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'), value=21.5, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=7696814, locations_id=2099180), Latest(datetime=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'), value=28.5, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=7696815, locations_id=2099180), Latest(datetime=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'), value=4010.0, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=8562589, locations_id=2099180), Latest(datetime=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'), value=37.0, coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), sensors_id=8562586, locations_id=2099180)])

In [27]:
test = client.locations.get(locations_id=2099180)

In [28]:
test.results

[Location(id=2099180, name='La Matanza, Buenos Aires', locality=None, timezone='America/Argentina/Buenos_Aires', country=CountryBase(id=6, code='AR', name='Argentina'), owner=OwnerBase(id=16700, name='ACUMAR'), provider=ProviderBase(id=66, name='AirGradient'), is_mobile=False, is_monitor=False, instruments=[InstrumentBase(id=7, name='Unknown AirGradient Sensor')], sensors=[SensorBase(id=8562534, name='pm1 µg/m³', parameter=ParameterBase(id=19, name='pm1', units='µg/m³', display_name='PM1')), SensorBase(id=8562542, name='pm10 µg/m³', parameter=ParameterBase(id=1, name='pm10', units='µg/m³', display_name='PM10')), SensorBase(id=7696815, name='pm25 µg/m³', parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name='PM2.5')), SensorBase(id=8562586, name='relativehumidity %', parameter=ParameterBase(id=98, name='relativehumidity', units='%', display_name='RH')), SensorBase(id=7696814, name='temperature c', parameter=ParameterBase(id=100, name='temperature', units='c', display_name='Temperature (C)')), SensorBase(id=8562589, name='um003 particles/cm³', parameter=ParameterBase(id=125, name='um003', units='particles/cm³', display_name='PM0.3 count'))], coordinates=Coordinates(latitude=-34.88106631929777, longitude=-58.68288039022074), bounds=(-58.68288039022074, -34.88106631929777, -58.68288039022074, -34.88106631929777), distance=None, datetime_first=Datetime(utc='2024-01-15T15:00:00Z', local='2024-01-15T12:00:00-03:00'), datetime_last=Datetime(utc='2026-09-26T00:00:00Z', local='2026-09-25T21:00:00-03:00'))]

In [6]:
from datetime import datetime, timedelta, timezone

today = datetime.now(timezone.utc)
ago_30 = today - timedelta(days=30)

In [ ]:
monthly_matanza = client.measurements.list(sensors_id=7696815,data="hours",datetime_from=ago_30,datetime_to=today,limit=1000)

In [8]:
first_measure = monthly_matanza.results[1]
print(f"Coverage: {first_measure}")

Coverage: Measurement(period=Period(label='1hour', interval='01:00:00', datetime_from=Datetime(utc='2026-08-25T22:00:00Z', local='2026-08-25T19:00:00-03:00'), datetime_to=Datetime(utc='2026-08-25T23:00:00Z', local='2026-08-25T20:00:00-03:00')), value=33.2, parameter=ParameterBase(id=2, name='pm25', units='µg/m³', display_name=None), coordinates=None, summary=Summary(min=33.2, q02=33.2, q25=33.2, median=33.2, q75=33.2, q98=33.2, max=33.2, sd=None, avg=33.2), coverage=Coverage(expected_count=1, expected_interval='01:00:00', observed_count=1, observed_interval='01:00:00', percent_complete=100.0, percent_coverage=100.0, datetime_from=Datetime(utc='2026-08-25T22:00:00Z', local='2026-08-25T19:00:00-03:00'), datetime_to=Datetime(utc='2026-08-25T23:00:00Z', local='2026-08-25T20:00:00-03:00')))

In [12]:
len(monthly_matanza.results)

719

In [19]:
test1 = test.results[0]
test1.datetime_first

Datetime(utc='2023-07-13T13:00:00Z', local='2023-07-13T10:00:00-03:00')

In [22]:
first_measure.parameter.units

'µg/m³'